kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: overlaytest-e2e
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: ClusterConfiguration
    networking:
      serviceSubnet: "10.96.0.0/16"
      podSubnet: "10.244.0.0/16"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-type=worker"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-type=worker"
networking:
  disableDefaultCNI: false
  kubeProxyMode: "iptables"
  ipFamily: ipv4
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443