name: End2End Testing
on:
  push:

jobs:
  end2end:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Set up K3S
      uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'v1.21.2-k3s1'
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Check Cluster
      run: |
        kubectl get nodes
    - name: Check overlay
      run: |
        go mod tidy
        kubectl get nodes
        go run overlay.go --help
        go run overlay.go --version
        go run overlay.go
