# .github/workflows/test.yml
name: Go Unit Tests

on:
  push:
    branches:
      - feat/unittests
  pull_request:
    branches:
      - feat/unittests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.23"
    - name: Install dependencies
      run: go mod tidy
    - name: Run tests
      #run: go test -v ./... -coverprofile=coverage.out
      run: go test -coverprofile=coverage.txt
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage.out
        flags: unittests
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: eumel8/overlaytest
    - name: Generate coverage badge
      run: go tool cover -func coverage.txt

